### ISSUE TITLE
USER STORY: View sign up

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlist-sharer#2]
As a **Site User** I can **see the sign up form** so that **I can sign up**

# Acceptance Criteria

 - Entering the signup address in a search engine displays the signup form
 - Clicking signup in the nav displays the signup form
 - Signup form has fields for username, an optional email, password and password confirmation

# Tasks

- [x] Create test
- [x] Install and set up allauth
- [x] Add allauth urls to setlistsharer/urls.py
- [x] Add signup link in nav
