### ISSUE TITLE
USER STORY: Create a username and password

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlist-sharer#3]
As a **Site User** I can **create a username and password** so that **I can sign up to the site**

# Acceptance Criteria

 - User can view the sign up form
 - Form contains a field for Username, Password, Password Confirmation and a submit button
 - Username and Password are saved in a database
 - User entered information is verified

# Tasks

- [x] Install AllAuth
- [x] Update requirements.txt
- [ ]  Create accounts app
- [ ] Create tests
- [ ] Create the view code
- [ ] Create a template to render the view
- [ ] Connect up URLs in urls.py
- [ ] Verify user input data
- [ ] Add username and password to database
- [ ] Add HTML and CSS
