### ISSUE TITLE
USER STORY: View home page

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlist-sharer#4]
As a **Site User** I can **see the home page** so that **I can find information about the site and use its features**

# Acceptance Criteria

 - Entering the website address in a search engine displays the home page
 - The home page explains the purpose of the site and its features

# Tasks

- [x] Create test
- [x] Create home app
- [x] Create the view code
- [x] Create a  base template
- [x] Create a template to render the view
- [x] Connect up URLs in urls.py
- [ ] Add placeholder site explanation to home page
- [ ] Add HTML and CSS
- [ ] Add site explanation to home page
